<?php
declare(strict_types=1);
$config = require __DIR__ . '/config.php';
date_default_timezone_set((string)$config['timezone']);
if (session_status() !== PHP_SESSION_ACTIVE) {
    session_set_cookie_params(['lifetime'=>(int)($config['admin_session_seconds']??28800),'httponly'=>true,'secure'=>!empty($_SERVER['HTTPS'])&&$_SERVER['HTTPS']!=='off','samesite'=>'Lax']);
    session_start();
}
function cfg(?string $key=null){global $config;return $key===null?$config:($config[$key]??null);} function path_of(string $p=''):string{return __DIR__.($p!==''?'/'.ltrim($p,'/'):'');}
function h($v):string{return htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');} function json_out(array $v,int $s=200):void{http_response_code($s);header('Content-Type: application/json; charset=UTF-8');header('Cache-Control: no-store');echo json_encode($v,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);exit;}
function csrf():string{if(empty($_SESSION['seed_csrf']))$_SESSION['seed_csrf']=bin2hex(random_bytes(24));return $_SESSION['seed_csrf'];} function require_csrf():void{$v=(string)($_POST['csrf']??$_SERVER['HTTP_X_CSRF_TOKEN']??'');if(!hash_equals(csrf(),$v))json_out(['success'=>false,'error'=>'画面を再読み込みしてください。'],419);}
function db():PDO{static $pdo;if($pdo instanceof PDO)return $pdo;$d=cfg('db');$pdo=new PDO('mysql:host='.$d['host'].';port='.(int)($d['port']??3306).';dbname='.$d['name'].';charset=utf8mb4',$d['user'],$d['pass'],[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC,PDO::ATTR_EMULATE_PREPARES=>false]);return $pdo;}
function seed_table_exists():bool{try{return(bool)db()->query("SHOW TABLES LIKE 'seed_count_records'")->fetchColumn();}catch(Throwable $e){return false;}}
function require_seed_table():void{if(!seed_table_exists())throw new RuntimeException('Seed用テーブルがありません。database/migration_seed_morphology_v2_0.sqlをBreadと同じデータベースで実行してください。');}
function ensure_dirs():void{foreach(['uploads/original','uploads/result','uploads/preview','uploads/tmp','uploads/stages','runtime/locks','runtime/logs']as$d){$p=path_of($d);if(!is_dir($p)&&!mkdir($p,0755,true)&&!is_dir($p))throw new RuntimeException('保存先を作成できません: '.$d);}}
function admin_ok():bool{if(empty($_SESSION['seed_admin']))return false;$limit=(int)(cfg('admin_session_seconds')??28800);$last=(int)($_SESSION['seed_admin_last']??0);if($last&&time()-$last>$limit){unset($_SESSION['seed_admin'],$_SESSION['seed_admin_last']);return false;}$_SESSION['seed_admin_last']=time();return true;} function require_admin():void{if(!admin_ok()){header('Location: admin.php');exit;}}
function seed_defaults():array{return ['threshold_value'=>-1,'foreground'=>'dark','min_area'=>100.0,'max_area'=>12000.0,'max_aspect'=>6.0,'min_solidity'=>0.55,'min_circularity'=>0.15,'max_circularity'=>1.2,'min_extent'=>0.25,'blur_size'=>5,'morph_kernel'=>3,'open_iterations'=>1,'close_iterations'=>1,'watershed_enabled'=>1,'distance_ratio'=>0.38,'watershed_bg_iterations'=>2,'clahe_enabled'=>0,'clahe_clip'=>2.0,'border_margin'=>2,'max_side'=>2000,'pixels_per_mm'=>0.0];}
function seed_settings():array{try{$r=db()->query('SELECT * FROM seed_count_settings WHERE id=1')->fetch();return $r?array_merge(seed_defaults(),$r):seed_defaults();}catch(Throwable $e){return seed_defaults();}}
function odd_seed_value($v,int $min=1,int $max=31):int{$n=max($min,min($max,(int)$v));return$n%2===0?min($max,$n+1):$n;}
function normalize_seed_settings(array $src,?array $base=null):array{$b=$base??seed_settings();$v=['threshold_value'=>max(-1,min(255,(int)($src['threshold_value']??$b['threshold_value']))),'foreground'=>(($src['foreground']??$b['foreground'])==='light')?'light':'dark','min_area'=>max(1,(float)($src['min_area']??$b['min_area'])),'max_area'=>max(10,(float)($src['max_area']??$b['max_area'])),'max_aspect'=>max(1,(float)($src['max_aspect']??$b['max_aspect'])),'min_solidity'=>max(0,min(1,(float)($src['min_solidity']??$b['min_solidity']))),'min_circularity'=>max(0,min(1.5,(float)($src['min_circularity']??$b['min_circularity']))),'max_circularity'=>max(0.01,min(1.5,(float)($src['max_circularity']??$b['max_circularity']))),'min_extent'=>max(0,min(1,(float)($src['min_extent']??$b['min_extent']))),'blur_size'=>odd_seed_value($src['blur_size']??$b['blur_size']),'morph_kernel'=>odd_seed_value($src['morph_kernel']??$b['morph_kernel']),'open_iterations'=>max(0,min(10,(int)($src['open_iterations']??$b['open_iterations']))),'close_iterations'=>max(0,min(10,(int)($src['close_iterations']??$b['close_iterations']))),'watershed_enabled'=>!empty($src)?(int)!empty($src['watershed_enabled']):(int)$b['watershed_enabled'],'distance_ratio'=>max(.05,min(.95,(float)($src['distance_ratio']??$b['distance_ratio']))),'watershed_bg_iterations'=>max(1,min(10,(int)($src['watershed_bg_iterations']??$b['watershed_bg_iterations']))),'clahe_enabled'=>!empty($src)?(int)!empty($src['clahe_enabled']):(int)$b['clahe_enabled'],'clahe_clip'=>max(.1,min(10,(float)($src['clahe_clip']??$b['clahe_clip']))),'border_margin'=>max(0,min(100,(int)($src['border_margin']??$b['border_margin']))),'max_side'=>max(500,min(5000,(int)($src['max_side']??$b['max_side']))),'pixels_per_mm'=>max(0,min(10000,(float)($src['pixels_per_mm']??$b['pixels_per_mm'])))];if($v['min_area']>=$v['max_area'])throw new RuntimeException('最小面積は最大面積より小さくしてください。');if($v['min_circularity']>$v['max_circularity'])throw new RuntimeException('最小円形度は最大円形度以下にしてください。');return$v;}
function seed_python_args(string $input,string $output,array $s,string $stageDir=''):array{foreach(['roi_x','roi_y','roi_w','roi_h']as$k){$s[$k]=max(0.0,min(1.0,(float)($s[$k]??$_POST[$k]??0)));}if($s['roi_x']+$s['roi_w']>1)$s['roi_w']=1-$s['roi_x'];if($s['roi_y']+$s['roi_h']>1)$s['roi_h']=1-$s['roi_y'];$saved=seed_settings();$method=(string)($_POST['threshold_method']??$saved['threshold_method']??((int)$s['threshold_value']<0?'otsu':'manual'));if(!in_array($method,['otsu','manual','adaptive'],true))$method='otsu';$bg=!empty($_POST)?!empty($_POST['background_correction']):!empty($saved['background_correction']);$backgroundKernel=odd_seed_value($_POST['background_kernel']??$saved['background_kernel']??101,31,301);$adaptiveBlock=odd_seed_value($_POST['adaptive_block']??$saved['adaptive_block']??51,3,151);$adaptiveC=max(-30,min(30,(float)($_POST['adaptive_c']??$saved['adaptive_c']??5)));$peakKernel=odd_seed_value($_POST['peak_kernel']??$saved['peak_kernel']??21,3,101);$a=[$input,$output,'--threshold',(string)$s['threshold_value'],'--threshold-method',$method,'--foreground',$s['foreground'],'--min-area',(string)$s['min_area'],'--max-area',(string)$s['max_area'],'--max-aspect',(string)$s['max_aspect'],'--min-solidity',(string)$s['min_solidity'],'--min-circularity',(string)$s['min_circularity'],'--max-circularity',(string)$s['max_circularity'],'--min-extent',(string)$s['min_extent'],'--blur',(string)$s['blur_size'],'--morph-kernel',(string)$s['morph_kernel'],'--open-iterations',(string)$s['open_iterations'],'--close-iterations',(string)$s['close_iterations'],'--distance-ratio',(string)$s['distance_ratio'],'--watershed-bg-iterations',(string)$s['watershed_bg_iterations'],'--clahe-clip',(string)$s['clahe_clip'],'--background-kernel',(string)$backgroundKernel,'--adaptive-block',(string)$adaptiveBlock,'--adaptive-c',(string)$adaptiveC,'--peak-kernel',(string)$peakKernel,'--border-margin',(string)$s['border_margin'],'--max-side',(string)$s['max_side'],'--pixels-per-mm',(string)$s['pixels_per_mm'],'--roi-x',(string)$s['roi_x'],'--roi-y',(string)$s['roi_y'],'--roi-w',(string)$s['roi_w'],'--roi-h',(string)$s['roi_h']];if($s['watershed_enabled'])$a[]='--watershed';if($s['clahe_enabled'])$a[]='--clahe';if($bg)$a[]='--background-correction';if($stageDir!==''){$a[]='--stage-dir';$a[]=$stageDir;}return$a;}
function save_v22_settings(array $src):void{$method=(string)($src['threshold_method']??'otsu');if(!in_array($method,['otsu','manual','adaptive'],true))$method='otsu';$sql='UPDATE seed_count_settings SET threshold_method=?,background_correction=?,background_kernel=?,adaptive_block=?,adaptive_c=?,peak_kernel=? WHERE id=1';db()->prepare($sql)->execute([$method,(int)!empty($src['background_correction']),odd_seed_value($src['background_kernel']??101,31,301),odd_seed_value($src['adaptive_block']??51,3,151),max(-30,min(30,(float)($src['adaptive_c']??5))),odd_seed_value($src['peak_kernel']??21,3,101)]);}
function save_seed_settings(array $s):void{require_seed_table();$sql='INSERT INTO seed_count_settings(id,threshold_value,foreground,min_area,max_area,max_aspect,min_solidity,min_circularity,max_circularity,min_extent,blur_size,morph_kernel,open_iterations,close_iterations,watershed_enabled,distance_ratio,watershed_bg_iterations,clahe_enabled,clahe_clip,border_margin,max_side,pixels_per_mm,allow_student_edit) VALUES(1,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,0) ON DUPLICATE KEY UPDATE threshold_value=VALUES(threshold_value),foreground=VALUES(foreground),min_area=VALUES(min_area),max_area=VALUES(max_area),max_aspect=VALUES(max_aspect),min_solidity=VALUES(min_solidity),min_circularity=VALUES(min_circularity),max_circularity=VALUES(max_circularity),min_extent=VALUES(min_extent),blur_size=VALUES(blur_size),morph_kernel=VALUES(morph_kernel),open_iterations=VALUES(open_iterations),close_iterations=VALUES(close_iterations),watershed_enabled=VALUES(watershed_enabled),distance_ratio=VALUES(distance_ratio),watershed_bg_iterations=VALUES(watershed_bg_iterations),clahe_enabled=VALUES(clahe_enabled),clahe_clip=VALUES(clahe_clip),border_margin=VALUES(border_margin),max_side=VALUES(max_side),pixels_per_mm=VALUES(pixels_per_mm),allow_student_edit=0';db()->prepare($sql)->execute([$s['threshold_value'],$s['foreground'],$s['min_area'],$s['max_area'],$s['max_aspect'],$s['min_solidity'],$s['min_circularity'],$s['max_circularity'],$s['min_extent'],$s['blur_size'],$s['morph_kernel'],$s['open_iterations'],$s['close_iterations'],$s['watershed_enabled'],$s['distance_ratio'],$s['watershed_bg_iterations'],$s['clahe_enabled'],$s['clahe_clip'],$s['border_margin'],$s['max_side'],$s['pixels_per_mm']]);}
function acquire_slot(){ensure_dirs();$end=microtime(true)+(int)cfg('analysis_slot_wait_seconds');do{for($i=1;$i<=(int)cfg('max_concurrent_analyses');$i++){$fp=fopen(path_of("runtime/locks/seed_slot_$i.lock"),'c');if($fp&&flock($fp,LOCK_EX|LOCK_NB))return$fp;if(is_resource($fp))fclose($fp);}usleep(250000);}while(microtime(true)<$end);return null;}
function run_python(array $args):array{$p=cfg('python');$cmd=escapeshellarg($p['binary']).' '.escapeshellarg($p['script']);foreach($args as$a)$cmd.=' '.escapeshellarg((string)$a);$cmd.=' 2>&1';$raw='';$exit=1;if(function_exists('proc_open')){$proc=proc_open($cmd,[1=>['pipe','w'],2=>['pipe','w']],$pipes,__DIR__);if(is_resource($proc)){stream_set_blocking($pipes[1],false);stream_set_blocking($pipes[2],false);$start=microtime(true);while(true){$raw.=stream_get_contents($pipes[1]).stream_get_contents($pipes[2]);$st=proc_get_status($proc);if(!$st['running'])break;if(microtime(true)-$start>(int)$p['timeout_seconds']){proc_terminate($proc,9);throw new RuntimeException('解析が制限時間を超えました。');}usleep(100000);}foreach($pipes as$x){$raw.=stream_get_contents($x);fclose($x);}$exit=proc_close($proc);if($exit===-1&&isset($st['exitcode']))$exit=$st['exitcode'];}}elseif(function_exists('exec')){$lines=[];exec($cmd,$lines,$exit);$raw=implode("\n",$lines);}else throw new RuntimeException('PHPからPythonを実行できません。');$data=json_decode(trim($raw),true);if(!is_array($data))throw new RuntimeException('解析エンジンから正しいJSONが返りませんでした。');if($exit!==0||empty($data['success']))throw new RuntimeException((string)($data['error']??'画像解析に失敗しました。'));return$data;}
function cleanup_tmp():void{$limit=time()-(int)cfg('job_retention_hours')*3600;foreach(['uploads/tmp/*','uploads/preview/*']as$pattern)foreach(glob(path_of($pattern))?:[]as$p)if(is_file($p)&&filemtime($p)<$limit)@unlink($p);}
