<?php
declare(strict_types=1);require __DIR__.'/bootstrap.php';$settings=seed_settings();$isAdmin=admin_ok();$defaults=seed_defaults();$sourceRecord=null;$sourceId=(int)($_GET['reanalyze']??0);if($sourceId>0){require_admin();$st=db()->prepare('SELECT * FROM seed_count_records WHERE id=?');$st->execute([$sourceId]);$sourceRecord=$st->fetch();if(!$sourceRecord){http_response_code(404);exit('再解析元の記録がありません');}$old=json_decode((string)($sourceRecord['settings_json']??''),true)?:[];if(isset($old['threshold']))$old['threshold_value']=($old['threshold_source']??'')==='manual'?$old['threshold']:-1;$settings=array_merge($settings,$old);}?><!doctype html><html lang="ja"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?=h(cfg('app_name'))?></title><link rel="stylesheet" href="assets/style.css?v=2.4.0"></head><body>
<header><div><small>RESEARCH PLATFORM</small><h1>🌾 Seed Morphology Analyzer</h1><p>粒数と種子ごとの形態をOpenCVで測定します。</p></div><nav><a href="index.php">画像解析</a><?php if($isAdmin):?><a href="settings.php">解析設定</a><a href="history.php">履歴</a><a href="diagnose.php">環境診断</a><a href="admin.php?logout=1">管理モード終了</a><?php else:?><a href="admin.php">管理モード</a><?php endif;?><?php if(cfg('bread_url')):?><a href="<?=h(cfg('bread_url'))?>">🍞 Bread解析</a><?php endif;?></nav></header>
<main><?php if($isAdmin):?><section class="admin-banner"><b>管理モード中</b><span>パラメータ調整・ライブプレビュー・既定値保存を利用できます。</span></section><?php endif;?><section class="card tips"><b>撮影のコツ</b><span>白い無地背景、真上から撮影、強い影を避け、可能なら種子を少し離してください。接触粒はWatershedで分離します。</span></section>
<?php if($sourceRecord):?><section class="card admin-banner"><b>履歴 #<?=$sourceId?> を再解析</b><span>元画像と当時の条件を、新規解析と同じ画面へ読み込みました。必要に応じて画像・ROI・条件を変更できます。</span></section><?php endif;?><form id="form" class="card" data-admin="<?=$isAdmin?'1':'0'?>"><label>試料名・班名<input name="device_name" maxlength="100" placeholder="品種A 3班" value="<?=h($sourceRecord['device_name']??'')?>"></label><label>メモ<input name="memo" maxlength="255" placeholder="試料番号、処理区など" value="<?=h($sourceRecord['memo']??'')?>"></label><?php if($sourceRecord):?><input type="hidden" name="source_record_id" value="<?=$sourceId?>"><?php endif;?><label class="upload">📱 <?= $sourceRecord?'別の画像へ変更（任意）':'写真を撮影・写真ライブラリ・ファイルから選択' ?><input id="photo" name="photo" type="file" accept="image/jpeg,image/png,image/webp,.jpg,.jpeg,.png,.webp" <?=$sourceRecord?'':'required'?>></label><small class="muted">JPEG・PNG・WebP、最大 <?=number_format((int)cfg('max_upload_bytes')/1024/1024)?>MB</small><img id="preview" class="preview<?=$sourceRecord?'':' hidden'?>" src="<?=$sourceRecord?h($sourceRecord['original_path']):''?>" alt="撮影画像">
<?php if($isAdmin):?><details class="manual-panel" open><summary>形態解析パラメータを手動調整</summary><div class="parameter-grid">
<label>二値化<select name="threshold_method" id="thresholdMode"><option value="otsu" <?=($settings['threshold_method']??'otsu')==='otsu'?'selected':''?>>Otsu自動</option><option value="manual" <?=($settings['threshold_method']??'otsu')==='manual'?'selected':''?>>手動</option><option value="adaptive" <?=($settings['threshold_method']??'otsu')==='adaptive'?'selected':''?>>Adaptive（照明ムラ向け）</option></select><small>影や明るさのムラがある写真はAdaptiveを試します。</small></label>
<label>手動しきい値 <output data-for="threshold_value"><?=max(0,(int)$settings['threshold_value'])?></output><input data-live type="range" name="threshold_value" min="0" max="255" step="1" value="<?=max(0,(int)$settings['threshold_value'])?>"><small>Otsu自動で不安定な場合だけ調整します。</small></label>
<label class="toggle"><input data-live type="checkbox" name="background_correction" value="1" <?=($settings['background_correction']??1)?'checked':''?>>背景・影補正<small>大きな明るさムラを推定して均一化します。</small></label>
<label>背景補正サイズ <output data-for="background_kernel"><?=h($settings['background_kernel']??101)?></output><input data-live type="range" name="background_kernel" min="31" max="301" step="2" value="<?=h($settings['background_kernel']??101)?>"><small>種子より十分大きい奇数。通常は101です。</small></label>
<label>Adaptive範囲 <output data-for="adaptive_block"><?=h($settings['adaptive_block']??51)?></output><input data-live type="range" name="adaptive_block" min="3" max="151" step="2" value="<?=h($settings['adaptive_block']??51)?>"><small>局所しきい値を計算する範囲です。</small></label>
<label>Adaptive補正値C <output data-for="adaptive_c"><?=h($settings['adaptive_c']??5)?></output><input data-live type="range" name="adaptive_c" min="-10" max="20" step="0.5" value="<?=h($settings['adaptive_c']??5)?>"><small>大きくすると検出領域が変化します。</small></label>
<label>局所ピーク範囲 <output data-for="peak_kernel"><?=h($settings['peak_kernel']??21)?></output><input data-live type="range" name="peak_kernel" min="3" max="101" step="2" value="<?=h($settings['peak_kernel']??21)?>"><small>小さいと分割が増え、大きいと分割が減ります。</small></label>
<label>対象色<select data-live name="foreground"><option value="dark" <?=$settings['foreground']==='dark'?'selected':''?>>背景より暗い</option><option value="light" <?=$settings['foreground']==='light'?'selected':''?>>背景より明るい</option></select><small>白背景の籾・玄米は通常「暗い」です。</small></label>
<label>最小面積 <output data-for="min_area"><?=h($settings['min_area'])?></output><input data-live type="range" name="min_area" min="1" max="2000" step="1" value="<?=h($settings['min_area'])?>"><small>小さなゴミを除外します。</small></label>
<label>最大面積 <output data-for="max_area"><?=h($settings['max_area'])?></output><input data-live type="range" name="max_area" min="1000" max="50000" step="100" value="<?=h($settings['max_area'])?>"><small>大きな影や塊を除外します。</small></label>
<label>最大長短径比 <output data-for="max_aspect"><?=h($settings['max_aspect'])?></output><input data-live type="range" name="max_aspect" min="1" max="12" step="0.1" value="<?=h($settings['max_aspect'])?>"><small>極端に細長いゴミを除外します。</small></label>
<label>最小充実度 <output data-for="min_solidity"><?=h($settings['min_solidity'])?></output><input data-live type="range" name="min_solidity" min="0" max="1" step="0.01" value="<?=h($settings['min_solidity'])?>"><small>凸包に対する輪郭の詰まり具合です。</small></label>
<label>最小円形度 <output data-for="min_circularity"><?=h($settings['min_circularity'])?></output><input data-live type="range" name="min_circularity" min="0" max="1.2" step="0.01" value="<?=h($settings['min_circularity'])?>"><small>低すぎる不規則形状を除外します。</small></label>
<label>最小Extent <output data-for="min_extent"><?=h($settings['min_extent'])?></output><input data-live type="range" name="min_extent" min="0" max="1" step="0.01" value="<?=h($settings['min_extent'])?>"><small>外接矩形に対する占有率です。</small></label>
<label class="toggle"><input data-live type="checkbox" name="watershed_enabled" value="1" <?=$settings['watershed_enabled']?'checked':''?>>Watershedを使用<small>接触した粒を距離変換のピークから分離します。</small></label>
<label>分離しきい値 <output data-for="distance_ratio"><?=h($settings['distance_ratio'])?></output><input data-live type="range" name="distance_ratio" min="0.05" max="0.95" step="0.01" value="<?=h($settings['distance_ratio'])?>"><small>上げると中心領域が狭くなり、分離数が変わります。</small></label>
<label class="toggle"><input data-live type="checkbox" name="clahe_enabled" value="1" <?=$settings['clahe_enabled']?'checked':''?>>CLAHE照明補正<small>照明ムラを局所コントラスト補正します。</small></label>
<label>ぼかし <output data-for="blur_size"><?=h($settings['blur_size'])?></output><input data-live type="range" name="blur_size" min="1" max="31" step="2" value="<?=h($settings['blur_size'])?>"><small>細かなノイズを低減します。</small></label>
<label>Morphology <output data-for="morph_kernel"><?=h($settings['morph_kernel'])?></output><input data-live type="range" name="morph_kernel" min="1" max="15" step="2" value="<?=h($settings['morph_kernel'])?>"><small>輪郭のノイズ除去・穴埋め範囲です。</small></label>
<label>Open回数 <output data-for="open_iterations"><?=h($settings['open_iterations'])?></output><input data-live type="range" name="open_iterations" min="0" max="5" step="1" value="<?=h($settings['open_iterations'])?>"></label><label>Close回数 <output data-for="close_iterations"><?=h($settings['close_iterations'])?></output><input data-live type="range" name="close_iterations" min="0" max="5" step="1" value="<?=h($settings['close_iterations'])?>"></label>
<label>1 mmあたりのpx <output data-for="pixels_per_mm"><?=h($settings['pixels_per_mm'])?></output><input data-live type="number" name="pixels_per_mm" min="0" max="10000" step="0.01" value="<?=h($settings['pixels_per_mm'])?>"><small>0は実寸換算なし。既知スケールから設定します。</small></label><label>解析最大辺 <output data-for="max_side"><?=h($settings['max_side'])?></output><input data-live type="range" name="max_side" min="500" max="4000" step="100" value="<?=h($settings['max_side'])?>"></label>
<input type="hidden" name="max_circularity" value="<?=h($settings['max_circularity'])?>"><input type="hidden" name="watershed_bg_iterations" value="<?=h($settings['watershed_bg_iterations'])?>"><input type="hidden" name="clahe_clip" value="<?=h($settings['clahe_clip'])?>"><input type="hidden" name="border_margin" value="<?=h($settings['border_margin'])?>"></div><div class="button-row"><label class="toggle"><input id="livePreview" type="checkbox">変更後に自動プレビュー</label><button type="button" id="previewButton" class="secondary">現在値でプレビュー</button><button type="button" id="resetButton" class="secondary">標準値へ戻す</button><button type="button" id="savedButton" class="secondary">保存済み値へ戻す</button><button type="button" id="saveSettingsButton" class="secondary">既定値として保存</button></div><div id="settingsStatus"></div></details><?php endif;?>
<input type="hidden" name="csrf" value="<?=h(csrf())?>"><button id="submit" class="primary">形態解析して保存</button><div id="status" role="status"></div></form>
<section id="result" class="card hidden"><div class="count"><span id="count">0</span><b>粒</b></div><p>処理時間 <span id="ms">-</span> ms／平均面積 <span id="meanArea">-</span> px²／平均長径 <span id="meanMajor">-</span> px</p><img id="resultImage" class="preview" alt="輪郭と番号付き解析結果"><div id="statsGrid" class="stats-grid"></div><details open><summary>個体別形態データ</summary><div class="table-wrap"><table><thead><tr><th>ID</th><th>面積</th><th>長径</th><th>短径</th><th>長短径比</th><th>円形度</th><th>充実度</th><th>向き</th></tr></thead><tbody id="objectRows"></tbody></table></div></details><p><a id="detailLink" class="secondary hidden" href="#">保存結果の詳細を見る</a></p><p id="resultNote" class="muted"></p></section></main>
<script>window.SEED_SOURCE_ID=<?=$sourceRecord?$sourceId:0?>;window.SEED_SOURCE_IMAGE=<?=json_encode($sourceRecord?$sourceRecord['original_path']:'',JSON_UNESCAPED_SLASHES)?>;window.SEED_SAVED_SETTINGS=<?=json_encode(array_merge(normalize_seed_settings([],$settings),$settings),JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES)?>;window.SEED_DEFAULT_SETTINGS=<?=json_encode(array_merge($defaults,['threshold_method'=>'otsu','background_correction'=>1,'background_kernel'=>101,'adaptive_block'=>51,'adaptive_c'=>5,'peak_kernel'=>21]),JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES)?>;</script><script src="assets/app.js?v=2.4.0"></script><script src="assets/zoom_fit.js?v=2.4.0"></script></body></html>
